import type { EquipmentId, ExerciseSeed, MovementPattern, MuscleId } from '@/domain';

/**
 * Seed exercise catalog (first 62 of ~150). Ids are stable slugs and never
 * change once shipped; renames are display names plus aliases.
 *
 * Numbers: stability 1 = machine-stabilised, 5 = free/unstable; difficulty and
 * fatigueCost 1–5. Increments are practical load steps in kg.
 */

type Partial = {
  id: string;
  name: string;
  aliases?: string[];
  pattern: MovementPattern;
  category?: 'compound' | 'isolation';
  equipment: EquipmentId[];
  laterality?: 'bilateral' | 'unilateral';
  loadType?: 'external' | 'bodyweight' | 'bodyweight_plus' | 'assisted';
  stability: number;
  difficulty: number;
  fatigue: number;
  reps?: [number, number];
  allowed?: [number, number];
  incrementKg?: number;
  primary: MuscleId[];
  secondary?: MuscleId[];
  setup: string[];
  execution: string[];
  cues: string[];
  mistakes: string[];
  progression?: string;
  regressions?: string[];
  alternatives?: string[];
};

function ex(p: Partial): ExerciseSeed {
  const isolation = p.category === 'isolation';
  return {
    id: p.id,
    name: p.name,
    aliases: p.aliases ?? [],
    movementPattern: p.pattern,
    category: p.category ?? 'compound',
    equipmentIds: p.equipment,
    laterality: p.laterality ?? 'bilateral',
    loadType: p.loadType ?? 'external',
    stability: p.stability,
    difficulty: p.difficulty,
    fatigueCost: p.fatigue,
    repRangeDefault: { min: p.reps?.[0] ?? (isolation ? 10 : 8), max: p.reps?.[1] ?? (isolation ? 15 : 12) },
    repRangeAllowed: { min: p.allowed?.[0] ?? (isolation ? 8 : 5), max: p.allowed?.[1] ?? 20 },
    incrementKg: p.incrementKg ?? (p.equipment.includes('barbell') || p.equipment.includes('smith') ? 2.5 : p.equipment.includes('machine') ? 5 : 2.5),
    muscles: [
      ...p.primary.map((m) => ({ muscleId: m, role: 'primary' as const, contribution: 1 })),
      ...(p.secondary ?? []).map((m) => ({ muscleId: m, role: 'secondary' as const, contribution: 0.5 })),
    ],
    instructions: { setup: p.setup, execution: p.execution, cues: p.cues, commonMistakes: p.mistakes },
    progressionNotes: p.progression,
    regressionIds: p.regressions ?? [],
    alternativeIds: p.alternatives ?? [],
  };
}

export const EXERCISE_SEED: ExerciseSeed[] = [
  // ---------------- Chest ----------------
  ex({
    id: 'barbell_bench_press',
    name: 'Barbell Bench Press',
    aliases: ['flat bench', 'bench press'],
    pattern: 'horizontal_push',
    equipment: ['barbell', 'bench', 'rack'],
    stability: 4,
    difficulty: 3,
    fatigue: 4,
    reps: [6, 10],
    allowed: [3, 15],
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Lie with eyes under the bar, feet flat and planted.', 'Grip slightly wider than shoulder width, wrists stacked over elbows.', 'Pull shoulder blades back and down; keep them pinned throughout.'],
    execution: ['Unrack and hold the bar over the shoulders.', 'Lower under control to the lower chest, elbows about 45° from the torso.', 'Press back up along a slight arc to the start.'],
    cues: ['Bend the bar', 'Leg drive into the floor', 'Chest up to the bar'],
    mistakes: ['Bouncing the bar off the chest', 'Elbows flared to 90°', 'Losing shoulder-blade position at the top'],
    progression: 'Add 2.5 kg once all sets reach the top of the range with reps in reserve.',
    regressions: ['dumbbell_bench_press', 'machine_chest_press'],
    alternatives: ['dumbbell_bench_press', 'machine_chest_press', 'smith_machine_bench_press'],
  }),
  ex({
    id: 'incline_barbell_bench_press',
    name: 'Incline Barbell Bench Press',
    aliases: ['incline bench'],
    pattern: 'horizontal_push',
    equipment: ['barbell', 'bench', 'rack'],
    stability: 4,
    difficulty: 3,
    fatigue: 4,
    reps: [6, 10],
    allowed: [4, 15],
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Set the bench to 30°.', 'Grip just outside shoulder width.', 'Retract the shoulder blades and plant the feet.'],
    execution: ['Lower the bar to the upper chest.', 'Press up and slightly back toward the face.'],
    cues: ['Elbows under the bar', 'Ribs down'],
    mistakes: ['Bench set too steep, turning it into a shoulder press', 'Lowering to the neck'],
    regressions: ['incline_dumbbell_press'],
    alternatives: ['incline_dumbbell_press', 'machine_chest_press'],
  }),
  ex({
    id: 'dumbbell_bench_press',
    name: 'Dumbbell Bench Press',
    aliases: ['flat DB press'],
    pattern: 'horizontal_push',
    equipment: ['dumbbell', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    allowed: [5, 20],
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Sit with dumbbells on the thighs, kick them up as you lie back.', 'Feet flat, shoulder blades pulled back.'],
    execution: ['Lower the dumbbells until the elbows are just below the bench.', 'Press up and slightly in without clanking the weights.'],
    cues: ['Elbows about 45° from the torso', 'Squeeze the chest at the top'],
    mistakes: ['Dropping the elbows too low and straining the shoulder', 'Letting the wrists bend back'],
    regressions: ['machine_chest_press', 'push_up'],
    alternatives: ['barbell_bench_press', 'machine_chest_press', 'incline_dumbbell_press'],
  }),
  ex({
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    aliases: ['incline DB press'],
    pattern: 'horizontal_push',
    equipment: ['dumbbell', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    allowed: [5, 20],
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Bench at 30°.', 'Kick the dumbbells up and set the shoulder blades back.'],
    execution: ['Lower to the sides of the upper chest.', 'Press up until the arms are nearly straight.'],
    cues: ['Keep the forearms vertical', 'Chest tall'],
    mistakes: ['Setting the bench too steep', 'Pressing the dumbbells together too early'],
    regressions: ['machine_chest_press'],
    alternatives: ['incline_barbell_bench_press', 'machine_chest_press', 'dumbbell_bench_press'],
  }),
  ex({
    id: 'machine_chest_press',
    name: 'Machine Chest Press',
    aliases: ['chest press machine', 'seated chest press'],
    pattern: 'horizontal_push',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 5,
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Set the seat so the handles line up with the mid chest.', 'Shoulder blades back against the pad.'],
    execution: ['Press the handles forward until the arms are nearly straight.', 'Return slowly until the chest is stretched.'],
    cues: ['Drive through the palms', 'Chest stays proud'],
    mistakes: ['Seat too low, pushing from the shoulders', 'Shrugging the shoulders forward at the end'],
    alternatives: ['dumbbell_bench_press', 'barbell_bench_press', 'cable_fly'],
  }),
  ex({
    id: 'smith_machine_bench_press',
    name: 'Smith Machine Bench Press',
    pattern: 'horizontal_push',
    equipment: ['smith', 'bench'],
    stability: 2,
    difficulty: 2,
    fatigue: 3,
    reps: [6, 10],
    allowed: [4, 15],
    primary: ['chest'],
    secondary: ['front_delts', 'triceps'],
    setup: ['Place the bench so the bar lowers to the lower chest.', 'Grip slightly wider than shoulders.'],
    execution: ['Unhook, lower to the chest, press to lockout.'],
    cues: ['Shoulder blades pinned', 'Elbows about 45°'],
    mistakes: ['Bench positioned so the bar path hits the neck or belly'],
    alternatives: ['barbell_bench_press', 'machine_chest_press'],
  }),
  ex({
    id: 'cable_fly',
    name: 'Cable Fly',
    aliases: ['cable crossover'],
    pattern: 'shoulder_transverse',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    allowed: [8, 20],
    incrementKg: 2.5,
    primary: ['chest'],
    secondary: ['front_delts'],
    setup: ['Set the pulleys at about chest height.', 'Step forward into a staggered stance with a slight forward lean.'],
    execution: ['Bring the hands together in a wide arc with a soft elbow bend.', 'Return slowly until the chest is stretched.'],
    cues: ['Hug a tree', 'Elbows stay slightly bent the whole time'],
    mistakes: ['Turning it into a press by bending the elbows', 'Leaning so far the lower back arches'],
    alternatives: ['pec_deck', 'dumbbell_fly'],
  }),
  ex({
    id: 'pec_deck',
    name: 'Pec Deck',
    aliases: ['machine fly', 'chest fly machine'],
    pattern: 'shoulder_transverse',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    allowed: [8, 20],
    incrementKg: 5,
    primary: ['chest'],
    secondary: ['front_delts'],
    setup: ['Seat height so the handles are at mid-chest.', 'Slight bend in the elbows.'],
    execution: ['Bring the arms together in front of the chest.', 'Open back up slowly to a comfortable stretch.'],
    cues: ['Squeeze at the middle', 'Control the return'],
    mistakes: ['Using momentum from the shoulders', 'Opening too far and straining the shoulder'],
    alternatives: ['cable_fly', 'dumbbell_fly'],
  }),
  ex({
    id: 'dumbbell_fly',
    name: 'Dumbbell Fly',
    pattern: 'shoulder_transverse',
    category: 'isolation',
    equipment: ['dumbbell', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 2,
    reps: [10, 15],
    primary: ['chest'],
    secondary: ['front_delts'],
    setup: ['Lie flat with dumbbells over the chest, palms facing.', 'Slight elbow bend that stays fixed.'],
    execution: ['Open the arms in a wide arc until the chest stretches.', 'Bring them back over the chest.'],
    cues: ['Wide arc, not a press'],
    mistakes: ['Going too deep with heavy weight', 'Letting the elbows bend more at the bottom'],
    alternatives: ['cable_fly', 'pec_deck'],
  }),
  ex({
    id: 'push_up',
    name: 'Push-Up',
    aliases: ['press-up'],
    pattern: 'horizontal_push',
    equipment: ['bodyweight'],
    loadType: 'bodyweight_plus',
    stability: 3,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 15],
    allowed: [5, 30],
    incrementKg: 2.5,
    primary: ['chest'],
    secondary: ['front_delts', 'triceps', 'abs'],
    setup: ['Hands just outside shoulder width, body in a straight line.'],
    execution: ['Lower the chest to just above the floor.', 'Press back up to full lockout.'],
    cues: ['Squeeze the glutes', 'Elbows at about 45°'],
    mistakes: ['Hips sagging', 'Half-range reps'],
    progression: 'Add reps to the top of the range, then add load with a plate or vest.',
    alternatives: ['dumbbell_bench_press', 'machine_chest_press'],
  }),
  ex({
    id: 'dip',
    name: 'Dip',
    aliases: ['parallel bar dip', 'chest dip'],
    pattern: 'vertical_push',
    equipment: ['dip_station'],
    loadType: 'bodyweight_plus',
    stability: 4,
    difficulty: 3,
    fatigue: 3,
    reps: [6, 12],
    allowed: [4, 20],
    incrementKg: 2.5,
    primary: ['chest', 'triceps'],
    secondary: ['front_delts'],
    setup: ['Support yourself on the bars with arms locked.', 'Lean forward slightly for chest emphasis.'],
    execution: ['Lower until the upper arms are about parallel.', 'Press back up to lockout.'],
    cues: ['Shoulders down away from the ears'],
    mistakes: ['Going too deep with cold shoulders', 'Shrugging at the top'],
    regressions: ['push_up', 'machine_chest_press'],
    alternatives: ['close_grip_bench_press', 'machine_chest_press'],
  }),

  // ---------------- Back ----------------
  ex({
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    aliases: ['pulldown'],
    pattern: 'vertical_pull',
    equipment: ['cable'],
    stability: 2,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 2.5,
    primary: ['lats'],
    secondary: ['upper_back', 'biceps', 'rear_delts'],
    setup: ['Thigh pad snug.', 'Grip just outside shoulder width, slight lean back.'],
    execution: ['Pull the bar to the upper chest by driving the elbows down.', 'Return until the arms are straight and the lats stretch.'],
    cues: ['Elbows to the back pockets', 'Chest up'],
    mistakes: ['Leaning back and heaving', 'Pulling to the belly'],
    alternatives: ['pull_up', 'machine_pulldown', 'chin_up'],
  }),
  ex({
    id: 'machine_pulldown',
    name: 'Machine Pulldown',
    aliases: ['plate-loaded pulldown', 'iso-lateral pulldown'],
    pattern: 'vertical_pull',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    incrementKg: 5,
    primary: ['lats'],
    secondary: ['upper_back', 'biceps'],
    setup: ['Seat so the handles start with the arms nearly straight overhead.'],
    execution: ['Drive the elbows down and back.', 'Return slowly to a full stretch.'],
    cues: ['Lead with the elbows'],
    mistakes: ['Short range at the top'],
    alternatives: ['lat_pulldown', 'pull_up'],
  }),
  ex({
    id: 'pull_up',
    name: 'Pull-Up',
    pattern: 'vertical_pull',
    equipment: ['pullup_bar'],
    loadType: 'bodyweight_plus',
    stability: 4,
    difficulty: 3,
    fatigue: 3,
    reps: [5, 10],
    allowed: [3, 15],
    incrementKg: 2.5,
    primary: ['lats'],
    secondary: ['upper_back', 'biceps', 'rear_delts'],
    setup: ['Overhand grip just outside shoulder width.', 'Hang with the shoulders engaged, not slack.'],
    execution: ['Pull until the chin clears the bar.', 'Lower under control to a full hang.'],
    cues: ['Elbows down to the ribs', 'Chest to the bar'],
    mistakes: ['Kipping', 'Stopping short of a full hang'],
    progression: 'Add reps to the top of the range, then add weight with a belt.',
    regressions: ['lat_pulldown', 'assisted_pull_up'],
    alternatives: ['lat_pulldown', 'chin_up', 'machine_pulldown'],
  }),
  ex({
    id: 'assisted_pull_up',
    name: 'Assisted Pull-Up',
    pattern: 'vertical_pull',
    equipment: ['machine'],
    loadType: 'assisted',
    stability: 2,
    difficulty: 1,
    fatigue: 2,
    reps: [6, 12],
    incrementKg: 2.5,
    primary: ['lats'],
    secondary: ['upper_back', 'biceps'],
    setup: ['Kneel on the pad; set the assistance so the top of the range is hard.'],
    execution: ['Pull until the chin clears the handles, lower fully.'],
    cues: ['Same path as a real pull-up'],
    mistakes: ['Too much assistance for the whole set'],
    progression: 'Reduce the assistance over time; move to pull-ups when assistance is minimal.',
    alternatives: ['lat_pulldown', 'pull_up'],
  }),
  ex({
    id: 'chin_up',
    name: 'Chin-Up',
    pattern: 'vertical_pull',
    equipment: ['pullup_bar'],
    loadType: 'bodyweight_plus',
    stability: 4,
    difficulty: 3,
    fatigue: 3,
    reps: [5, 10],
    allowed: [3, 15],
    incrementKg: 2.5,
    primary: ['lats', 'biceps'],
    secondary: ['upper_back'],
    setup: ['Underhand grip at shoulder width.'],
    execution: ['Pull until the chin clears the bar, lower to a full hang.'],
    cues: ['Squeeze the biceps at the top'],
    mistakes: ['Swinging', 'Half reps'],
    regressions: ['lat_pulldown', 'assisted_pull_up'],
    alternatives: ['pull_up', 'lat_pulldown'],
  }),
  ex({
    id: 'barbell_row',
    name: 'Barbell Row',
    aliases: ['bent-over row'],
    pattern: 'horizontal_pull',
    equipment: ['barbell'],
    stability: 5,
    difficulty: 4,
    fatigue: 4,
    reps: [6, 10],
    allowed: [5, 15],
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts', 'spinal_erectors'],
    setup: ['Hinge to about 45° with a flat back, bar over mid-foot.', 'Grip just outside the knees.'],
    execution: ['Row the bar to the lower chest or upper stomach.', 'Lower under control without rounding.'],
    cues: ['Brace hard', 'Elbows back, not out'],
    mistakes: ['Standing up to heave the weight', 'Rounding the lower back'],
    regressions: ['chest_supported_row', 'seated_cable_row'],
    alternatives: ['chest_supported_row', 'seated_cable_row', 'machine_row'],
  }),
  ex({
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    aliases: ['incline dumbbell row', 'seal row'],
    pattern: 'horizontal_pull',
    equipment: ['dumbbell', 'bench'],
    stability: 2,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    setup: ['Bench at about 30–45°, chest on the pad, dumbbells hanging.'],
    execution: ['Row the elbows up and back.', 'Lower to a full stretch.'],
    cues: ['Squeeze the shoulder blades', 'Chest stays on the pad'],
    mistakes: ['Lifting the chest off the pad', 'Shrugging'],
    alternatives: ['machine_row', 'seated_cable_row', 'barbell_row'],
  }),
  ex({
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    aliases: ['cable row'],
    pattern: 'horizontal_pull',
    equipment: ['cable'],
    stability: 2,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 2.5,
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    setup: ['Feet on the platform, slight knee bend, tall torso.'],
    execution: ['Pull the handle to the stomach, elbows close.', 'Return until the shoulder blades protract.'],
    cues: ['Chest up as you pull', 'Let the lats stretch at the front'],
    mistakes: ['Rocking the torso', 'Pulling with the arms only'],
    alternatives: ['machine_row', 'chest_supported_row', 'single_arm_dumbbell_row'],
  }),
  ex({
    id: 'machine_row',
    name: 'Machine Row',
    aliases: ['plate-loaded row', 'iso-lateral row'],
    pattern: 'horizontal_pull',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    incrementKg: 5,
    primary: ['upper_back', 'lats'],
    secondary: ['biceps', 'rear_delts'],
    setup: ['Chest against the pad, handles at about chest height.'],
    execution: ['Drive the elbows back, squeeze, and return with control.'],
    cues: ['Elbows back, chest on the pad'],
    mistakes: ['Pulling the chest off the pad'],
    alternatives: ['seated_cable_row', 'chest_supported_row'],
  }),
  ex({
    id: 'single_arm_dumbbell_row',
    name: 'Single-Arm Dumbbell Row',
    aliases: ['one-arm row'],
    pattern: 'horizontal_pull',
    equipment: ['dumbbell', 'bench'],
    laterality: 'unilateral',
    stability: 3,
    difficulty: 2,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    primary: ['lats', 'upper_back'],
    secondary: ['biceps', 'rear_delts'],
    setup: ['One knee and hand on the bench, back flat, dumbbell hanging.'],
    execution: ['Row the elbow up toward the hip.', 'Lower to a full stretch.'],
    cues: ['Elbow to the hip, not the ceiling', 'No torso twist'],
    mistakes: ['Rotating the torso to lift more', 'Shrugging the shoulder'],
    alternatives: ['chest_supported_row', 'seated_cable_row'],
  }),
  ex({
    id: 'face_pull',
    name: 'Face Pull',
    pattern: 'horizontal_pull',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [12, 20],
    allowed: [10, 25],
    incrementKg: 2.5,
    primary: ['rear_delts', 'upper_back'],
    secondary: ['traps'],
    setup: ['Rope at face height, overhand grip, step back.'],
    execution: ['Pull the rope toward the face, hands finishing by the ears.', 'Return slowly.'],
    cues: ['Pull apart, not just back', 'Elbows high'],
    mistakes: ['Too heavy and leaning back', 'Elbows dropping'],
    alternatives: ['reverse_pec_deck', 'rear_delt_dumbbell_fly'],
  }),
  ex({
    id: 'straight_arm_pulldown',
    name: 'Straight-Arm Pulldown',
    aliases: ['cable pullover'],
    pattern: 'vertical_pull',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['lats'],
    secondary: ['triceps'],
    setup: ['High pulley, bar or rope, slight hinge, arms nearly straight.'],
    execution: ['Sweep the hands down to the thighs.', 'Return overhead to a stretch.'],
    cues: ['Elbows locked in a soft bend'],
    mistakes: ['Bending the elbows into a pushdown'],
    alternatives: ['lat_pulldown'],
  }),

  // ---------------- Shoulders ----------------
  ex({
    id: 'overhead_press',
    name: 'Barbell Overhead Press',
    aliases: ['OHP', 'military press', 'standing press'],
    pattern: 'vertical_push',
    equipment: ['barbell', 'rack'],
    stability: 5,
    difficulty: 4,
    fatigue: 4,
    reps: [5, 8],
    allowed: [3, 12],
    primary: ['front_delts'],
    secondary: ['side_delts', 'triceps', 'upper_back'],
    setup: ['Bar on the front shoulders, grip just outside shoulder width.', 'Squeeze the glutes and brace.'],
    execution: ['Press straight up, moving the head back then through.', 'Lock out over the mid-foot.'],
    cues: ['Head through the window', 'Ribs down'],
    mistakes: ['Leaning back and arching', 'Pressing forward around the face'],
    regressions: ['seated_dumbbell_shoulder_press', 'machine_shoulder_press'],
    alternatives: ['seated_dumbbell_shoulder_press', 'machine_shoulder_press'],
  }),
  ex({
    id: 'seated_dumbbell_shoulder_press',
    name: 'Seated Dumbbell Shoulder Press',
    aliases: ['DB shoulder press'],
    pattern: 'vertical_push',
    equipment: ['dumbbell', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    allowed: [5, 15],
    primary: ['front_delts'],
    secondary: ['side_delts', 'triceps'],
    setup: ['Bench upright, dumbbells at shoulder height, palms forward.'],
    execution: ['Press up until the arms are nearly straight.', 'Lower to about ear level.'],
    cues: ['Elbows slightly forward of the shoulders'],
    mistakes: ['Lowering too far and straining the shoulder', 'Arching to press'],
    alternatives: ['machine_shoulder_press', 'overhead_press'],
  }),
  ex({
    id: 'machine_shoulder_press',
    name: 'Machine Shoulder Press',
    pattern: 'vertical_push',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    incrementKg: 5,
    primary: ['front_delts'],
    secondary: ['side_delts', 'triceps'],
    setup: ['Seat so the handles start at about shoulder height.'],
    execution: ['Press to near lockout, lower with control.'],
    cues: ['Drive evenly with both arms'],
    mistakes: ['Seat too low'],
    alternatives: ['seated_dumbbell_shoulder_press', 'overhead_press'],
  }),
  ex({
    id: 'dumbbell_lateral_raise',
    name: 'Dumbbell Lateral Raise',
    aliases: ['side raise'],
    pattern: 'shoulder_abduction',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    allowed: [8, 25],
    incrementKg: 1,
    primary: ['side_delts'],
    setup: ['Stand tall, dumbbells at the sides, slight forward lean.'],
    execution: ['Raise the arms out to the sides to shoulder height.', 'Lower slowly.'],
    cues: ['Lead with the elbows', 'Pour the water out at the top'],
    mistakes: ['Swinging with the hips', 'Shrugging the traps'],
    alternatives: ['cable_lateral_raise', 'machine_lateral_raise'],
  }),
  ex({
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    pattern: 'shoulder_abduction',
    category: 'isolation',
    equipment: ['cable'],
    laterality: 'unilateral',
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    allowed: [8, 25],
    incrementKg: 1,
    primary: ['side_delts'],
    setup: ['Low pulley, handle in the far hand, cable crossing the body.'],
    execution: ['Raise the arm out to shoulder height, lower slowly.'],
    cues: ['Constant tension'],
    mistakes: ['Leaning away to cheat'],
    alternatives: ['dumbbell_lateral_raise', 'machine_lateral_raise'],
  }),
  ex({
    id: 'machine_lateral_raise',
    name: 'Machine Lateral Raise',
    pattern: 'shoulder_abduction',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['side_delts'],
    setup: ['Pads against the upper arms just above the elbows.'],
    execution: ['Raise the arms to shoulder height, lower under control.'],
    cues: ['Push with the elbows'],
    mistakes: ['Raising above shoulder height'],
    alternatives: ['dumbbell_lateral_raise', 'cable_lateral_raise'],
  }),
  ex({
    id: 'reverse_pec_deck',
    name: 'Reverse Pec Deck',
    aliases: ['rear delt machine'],
    pattern: 'horizontal_pull',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [12, 20],
    incrementKg: 2.5,
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    setup: ['Face the pad, handles in front at shoulder height.'],
    execution: ['Sweep the arms back in a wide arc.', 'Return slowly.'],
    cues: ['Lead with the elbows, not the hands'],
    mistakes: ['Squeezing the shoulder blades instead of moving the arms'],
    alternatives: ['face_pull', 'rear_delt_dumbbell_fly'],
  }),
  ex({
    id: 'rear_delt_dumbbell_fly',
    name: 'Rear Delt Dumbbell Fly',
    aliases: ['bent-over reverse fly'],
    pattern: 'horizontal_pull',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 4,
    difficulty: 2,
    fatigue: 1,
    reps: [12, 20],
    incrementKg: 1,
    primary: ['rear_delts'],
    secondary: ['upper_back'],
    setup: ['Hinge to near parallel, dumbbells hanging, soft elbows.'],
    execution: ['Raise the arms out to the sides, lower slowly.'],
    cues: ['Thumbs down slightly'],
    mistakes: ['Standing up during the set'],
    alternatives: ['reverse_pec_deck', 'face_pull'],
  }),

  // ---------------- Arms ----------------
  ex({
    id: 'barbell_curl',
    name: 'Barbell Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['barbell'],
    stability: 3,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    primary: ['biceps'],
    secondary: ['forearms'],
    setup: ['Stand tall, shoulder-width underhand grip.'],
    execution: ['Curl to the shoulders keeping the elbows by the sides.', 'Lower fully.'],
    cues: ['Elbows pinned', 'Full stretch at the bottom'],
    mistakes: ['Swinging the torso', 'Elbows drifting forward'],
    alternatives: ['ez_bar_curl', 'dumbbell_curl', 'cable_curl'],
  }),
  ex({
    id: 'ez_bar_curl',
    name: 'EZ Bar Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['ez_bar'],
    stability: 3,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    primary: ['biceps'],
    secondary: ['forearms'],
    setup: ['Grip the inner angles of the bar.'],
    execution: ['Curl to the shoulders, lower fully.'],
    cues: ['Elbows by the sides'],
    mistakes: ['Swinging'],
    alternatives: ['barbell_curl', 'dumbbell_curl'],
  }),
  ex({
    id: 'dumbbell_curl',
    name: 'Dumbbell Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 1,
    fatigue: 1,
    reps: [8, 12],
    primary: ['biceps'],
    secondary: ['forearms'],
    setup: ['Stand or sit, dumbbells at the sides, palms forward.'],
    execution: ['Curl both or alternating, lower under control.'],
    cues: ['Turn the pinky up at the top'],
    mistakes: ['Leaning back', 'Half reps'],
    alternatives: ['incline_dumbbell_curl', 'cable_curl', 'barbell_curl'],
  }),
  ex({
    id: 'incline_dumbbell_curl',
    name: 'Incline Dumbbell Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['dumbbell', 'bench'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [8, 12],
    primary: ['biceps'],
    setup: ['Bench at 45–60°, arms hanging straight down.'],
    execution: ['Curl without moving the upper arms, lower to a full stretch.'],
    cues: ['Let the arms hang behind the body'],
    mistakes: ['Bringing the elbows forward'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
  }),
  ex({
    id: 'hammer_curl',
    name: 'Hammer Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 1,
    fatigue: 1,
    reps: [8, 12],
    primary: ['biceps', 'forearms'],
    setup: ['Palms facing each other.'],
    execution: ['Curl to the shoulders, lower fully.'],
    cues: ['Thumbs up the whole way'],
    mistakes: ['Swinging'],
    alternatives: ['dumbbell_curl', 'cable_curl'],
  }),
  ex({
    id: 'cable_curl',
    name: 'Cable Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['biceps'],
    secondary: ['forearms'],
    setup: ['Low pulley, straight or EZ bar.'],
    execution: ['Curl to the shoulders, lower with constant tension.'],
    cues: ['Elbows still'],
    mistakes: ['Leaning back'],
    alternatives: ['dumbbell_curl', 'barbell_curl', 'preacher_curl'],
  }),
  ex({
    id: 'preacher_curl',
    name: 'Preacher Curl',
    pattern: 'elbow_flexion',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [8, 12],
    incrementKg: 2.5,
    primary: ['biceps'],
    setup: ['Upper arms flat on the pad, armpits at the top edge.'],
    execution: ['Curl up, lower almost to straight.'],
    cues: ['Do not lift the elbows off the pad'],
    mistakes: ['Bouncing at the bottom'],
    alternatives: ['cable_curl', 'incline_dumbbell_curl'],
  }),
  ex({
    id: 'triceps_pushdown',
    name: 'Triceps Pushdown',
    aliases: ['cable pushdown', 'rope pushdown'],
    pattern: 'elbow_extension',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['triceps'],
    setup: ['High pulley, rope or bar, elbows at the sides.'],
    execution: ['Extend the elbows fully, return to about 90°.'],
    cues: ['Elbows pinned', 'Squeeze at lockout'],
    mistakes: ['Leaning over the cable to push with the shoulders'],
    alternatives: ['overhead_cable_triceps_extension', 'skull_crusher', 'dumbbell_overhead_triceps_extension'],
  }),
  ex({
    id: 'overhead_cable_triceps_extension',
    name: 'Overhead Cable Triceps Extension',
    pattern: 'elbow_extension',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['triceps'],
    setup: ['Face away from a low or mid pulley, rope overhead, elbows by the ears.'],
    execution: ['Extend the arms overhead, return to a deep stretch.'],
    cues: ['Elbows stay narrow'],
    mistakes: ['Flaring the elbows out'],
    alternatives: ['dumbbell_overhead_triceps_extension', 'triceps_pushdown', 'skull_crusher'],
  }),
  ex({
    id: 'dumbbell_overhead_triceps_extension',
    name: 'Dumbbell Overhead Triceps Extension',
    pattern: 'elbow_extension',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    primary: ['triceps'],
    setup: ['Hold one dumbbell overhead with both hands, elbows narrow.'],
    execution: ['Lower behind the head to a stretch, extend to lockout.'],
    cues: ['Elbows point forward'],
    mistakes: ['Arching the lower back'],
    alternatives: ['overhead_cable_triceps_extension', 'triceps_pushdown'],
  }),
  ex({
    id: 'skull_crusher',
    name: 'Skull Crusher',
    aliases: ['lying triceps extension'],
    pattern: 'elbow_extension',
    category: 'isolation',
    equipment: ['ez_bar', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 2,
    reps: [8, 12],
    primary: ['triceps'],
    setup: ['Lie flat, bar over the forehead with a narrow grip.'],
    execution: ['Lower the bar toward the top of the head, extend back up.'],
    cues: ['Upper arms angled slightly back and still'],
    mistakes: ['Elbows flaring wide', 'Turning it into a press'],
    alternatives: ['triceps_pushdown', 'overhead_cable_triceps_extension', 'close_grip_bench_press'],
  }),
  ex({
    id: 'close_grip_bench_press',
    name: 'Close-Grip Bench Press',
    pattern: 'horizontal_push',
    equipment: ['barbell', 'bench', 'rack'],
    stability: 4,
    difficulty: 3,
    fatigue: 3,
    reps: [6, 10],
    allowed: [4, 15],
    primary: ['triceps'],
    secondary: ['chest', 'front_delts'],
    setup: ['Grip at about shoulder width, shoulder blades back.'],
    execution: ['Lower to the lower chest with elbows tucked, press to lockout.'],
    cues: ['Elbows close to the body'],
    mistakes: ['Grip so narrow the wrists hurt'],
    alternatives: ['dip', 'skull_crusher'],
  }),

  // ---------------- Legs ----------------
  ex({
    id: 'barbell_back_squat',
    name: 'Barbell Back Squat',
    aliases: ['back squat', 'squat'],
    pattern: 'squat',
    equipment: ['barbell', 'rack'],
    stability: 5,
    difficulty: 4,
    fatigue: 5,
    reps: [5, 8],
    allowed: [3, 15],
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings', 'spinal_erectors'],
    setup: ['Bar on the upper back, hands close enough to keep the upper back tight.', 'Feet about shoulder width, toes slightly out.', 'Big breath, brace.'],
    execution: ['Sit down between the hips, knees tracking over the toes.', 'Descend to at least parallel.', 'Drive up keeping the chest up.'],
    cues: ['Spread the floor', 'Chest up, knees out'],
    mistakes: ['Knees caving in', 'Heels rising', 'Rounding the lower back at the bottom'],
    regressions: ['goblet_squat', 'leg_press', 'hack_squat'],
    alternatives: ['hack_squat', 'leg_press', 'smith_machine_squat', 'front_squat'],
  }),
  ex({
    id: 'front_squat',
    name: 'Front Squat',
    pattern: 'squat',
    equipment: ['barbell', 'rack'],
    stability: 5,
    difficulty: 5,
    fatigue: 4,
    reps: [5, 8],
    allowed: [3, 12],
    primary: ['quads'],
    secondary: ['glutes', 'adductors', 'abs', 'spinal_erectors'],
    setup: ['Bar on the front shoulders, elbows high.'],
    execution: ['Squat down keeping the torso upright, drive up.'],
    cues: ['Elbows up the whole rep'],
    mistakes: ['Elbows dropping and the bar rolling forward'],
    regressions: ['goblet_squat', 'hack_squat'],
    alternatives: ['hack_squat', 'barbell_back_squat', 'leg_press'],
  }),
  ex({
    id: 'hack_squat',
    name: 'Hack Squat',
    pattern: 'squat',
    equipment: ['machine'],
    stability: 2,
    difficulty: 2,
    fatigue: 4,
    reps: [8, 12],
    allowed: [5, 15],
    incrementKg: 5,
    primary: ['quads'],
    secondary: ['glutes', 'adductors'],
    setup: ['Back flat on the pad, feet mid-platform at shoulder width.'],
    execution: ['Lower until the thighs are at least parallel, drive through the whole foot.'],
    cues: ['Knees track over the toes', 'Do not lock out hard'],
    mistakes: ['Feet too low, pulling the heels up', 'Bouncing at the bottom'],
    alternatives: ['leg_press', 'smith_machine_squat', 'barbell_back_squat'],
  }),
  ex({
    id: 'leg_press',
    name: 'Leg Press',
    pattern: 'squat',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 3,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 10,
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings'],
    setup: ['Feet mid-platform, shoulder width, back and hips on the pad.'],
    execution: ['Lower until the knees are near 90° or the hips start to lift.', 'Press without locking the knees.'],
    cues: ['Hips stay down', 'Push through the mid-foot'],
    mistakes: ['Lowering so far the lower back rounds off the pad', 'Locking the knees hard'],
    alternatives: ['hack_squat', 'smith_machine_squat', 'barbell_back_squat'],
  }),
  ex({
    id: 'smith_machine_squat',
    name: 'Smith Machine Squat',
    pattern: 'squat',
    equipment: ['smith'],
    stability: 2,
    difficulty: 2,
    fatigue: 4,
    reps: [8, 12],
    allowed: [5, 15],
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings'],
    setup: ['Bar on the upper back, feet slightly in front of the bar.'],
    execution: ['Squat to parallel or below, drive up.'],
    cues: ['Lean into the bar slightly'],
    mistakes: ['Feet directly under the bar, forcing forward knee travel'],
    alternatives: ['hack_squat', 'leg_press', 'barbell_back_squat'],
  }),
  ex({
    id: 'goblet_squat',
    name: 'Goblet Squat',
    pattern: 'squat',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 1,
    fatigue: 2,
    reps: [10, 15],
    allowed: [8, 20],
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'abs'],
    setup: ['Hold a dumbbell vertically against the chest.'],
    execution: ['Squat between the knees keeping the torso tall, stand up.'],
    cues: ['Elbows inside the knees at the bottom'],
    mistakes: ['Letting the weight pull the chest forward'],
    alternatives: ['leg_press', 'hack_squat', 'bulgarian_split_squat'],
  }),
  ex({
    id: 'bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    aliases: ['rear-foot-elevated split squat'],
    pattern: 'lunge',
    equipment: ['dumbbell', 'bench'],
    laterality: 'unilateral',
    stability: 4,
    difficulty: 3,
    fatigue: 3,
    reps: [8, 12],
    allowed: [6, 15],
    primary: ['quads', 'glutes'],
    secondary: ['adductors', 'hamstrings'],
    setup: ['Rear foot on a bench, front foot far enough forward that the knee stays over the foot.'],
    execution: ['Lower until the rear knee is near the floor, drive up through the front foot.'],
    cues: ['Slight forward lean for glutes, upright for quads'],
    mistakes: ['Front foot too close', 'Pushing off the back foot'],
    alternatives: ['walking_lunge', 'leg_press', 'goblet_squat'],
  }),
  ex({
    id: 'walking_lunge',
    name: 'Walking Lunge',
    pattern: 'lunge',
    equipment: ['dumbbell'],
    laterality: 'unilateral',
    stability: 4,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'adductors'],
    setup: ['Dumbbells at the sides, tall posture.'],
    execution: ['Step forward, lower the back knee toward the floor, step through.'],
    cues: ['Long steps, soft landing'],
    mistakes: ['Short steps that strain the front knee'],
    alternatives: ['bulgarian_split_squat', 'leg_press'],
  }),
  ex({
    id: 'leg_extension',
    name: 'Leg Extension',
    pattern: 'knee_extension',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [10, 15],
    allowed: [8, 20],
    incrementKg: 5,
    primary: ['quads'],
    setup: ['Knee joint lined up with the machine pivot, pad on the lower shins.'],
    execution: ['Extend fully, lower under control.'],
    cues: ['Squeeze at the top for a beat'],
    mistakes: ['Kicking the weight up with momentum'],
    alternatives: ['hack_squat', 'leg_press'],
  }),
  ex({
    id: 'romanian_deadlift',
    name: 'Romanian Deadlift',
    aliases: ['RDL'],
    pattern: 'hinge',
    equipment: ['barbell'],
    stability: 4,
    difficulty: 3,
    fatigue: 4,
    reps: [6, 10],
    allowed: [5, 15],
    primary: ['hamstrings', 'glutes'],
    secondary: ['spinal_erectors', 'upper_back'],
    setup: ['Stand tall with the bar at the hips, soft knees.'],
    execution: ['Push the hips back, sliding the bar down the thighs.', 'Stop when the hamstrings are stretched, then drive the hips forward.'],
    cues: ['Bar stays close', 'Chest up, back flat'],
    mistakes: ['Squatting the weight down', 'Rounding the back'],
    regressions: ['dumbbell_romanian_deadlift', 'seated_leg_curl'],
    alternatives: ['dumbbell_romanian_deadlift', 'seated_leg_curl', 'lying_leg_curl'],
  }),
  ex({
    id: 'dumbbell_romanian_deadlift',
    name: 'Dumbbell Romanian Deadlift',
    aliases: ['DB RDL'],
    pattern: 'hinge',
    equipment: ['dumbbell'],
    stability: 4,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    primary: ['hamstrings', 'glutes'],
    secondary: ['spinal_erectors'],
    setup: ['Dumbbells in front of the thighs, soft knees.'],
    execution: ['Hinge until the hamstrings stretch, stand back up.'],
    cues: ['Hips back, not down'],
    mistakes: ['Rounding the back'],
    alternatives: ['romanian_deadlift', 'seated_leg_curl'],
  }),
  ex({
    id: 'conventional_deadlift',
    name: 'Conventional Deadlift',
    aliases: ['deadlift'],
    pattern: 'hinge',
    equipment: ['barbell'],
    stability: 5,
    difficulty: 5,
    fatigue: 5,
    reps: [3, 6],
    allowed: [1, 10],
    primary: ['glutes', 'hamstrings', 'spinal_erectors'],
    secondary: ['quads', 'upper_back', 'traps', 'forearms'],
    setup: ['Bar over mid-foot, shins an inch away.', 'Grip just outside the legs, hips high enough to keep the back flat.'],
    execution: ['Push the floor away, keeping the bar against the legs.', 'Lock out by squeezing the glutes, lower under control.'],
    cues: ['Wedge into the bar', 'Chest up before the pull'],
    mistakes: ['Hips shooting up first', 'Rounding the lower back'],
    regressions: ['trap_bar_deadlift', 'romanian_deadlift'],
    alternatives: ['trap_bar_deadlift', 'romanian_deadlift'],
  }),
  ex({
    id: 'trap_bar_deadlift',
    name: 'Trap Bar Deadlift',
    aliases: ['hex bar deadlift'],
    pattern: 'hinge',
    equipment: ['trap_bar'],
    stability: 4,
    difficulty: 3,
    fatigue: 4,
    reps: [5, 8],
    allowed: [3, 12],
    primary: ['glutes', 'quads', 'hamstrings'],
    secondary: ['spinal_erectors', 'traps', 'forearms'],
    setup: ['Stand centred in the bar, grip the handles.'],
    execution: ['Drive through the floor to stand tall, lower under control.'],
    cues: ['Chest up, push the floor'],
    mistakes: ['Squatting too low at the start'],
    alternatives: ['conventional_deadlift', 'romanian_deadlift', 'leg_press'],
  }),
  ex({
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    pattern: 'knee_flexion',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 5,
    primary: ['hamstrings'],
    setup: ['Knee lined up with the pivot, thigh pad snug, pad above the heels.'],
    execution: ['Curl the heels under the seat, return slowly.'],
    cues: ['Full stretch at the top'],
    mistakes: ['Lifting the hips to cheat'],
    alternatives: ['lying_leg_curl', 'romanian_deadlift'],
  }),
  ex({
    id: 'lying_leg_curl',
    name: 'Lying Leg Curl',
    pattern: 'knee_flexion',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 2,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 5,
    primary: ['hamstrings'],
    setup: ['Pad just above the heels, hips pressed into the bench.'],
    execution: ['Curl toward the glutes, lower slowly.'],
    cues: ['Hips down'],
    mistakes: ['Arching and lifting the hips'],
    alternatives: ['seated_leg_curl', 'romanian_deadlift'],
  }),
  ex({
    id: 'hip_thrust',
    name: 'Barbell Hip Thrust',
    pattern: 'hinge',
    equipment: ['barbell', 'bench'],
    stability: 3,
    difficulty: 2,
    fatigue: 3,
    reps: [8, 12],
    allowed: [6, 20],
    primary: ['glutes'],
    secondary: ['hamstrings', 'quads'],
    setup: ['Upper back on a bench, bar across the hips with a pad, feet flat.'],
    execution: ['Drive the hips up until the torso is level, squeeze, lower.'],
    cues: ['Chin tucked, ribs down', 'Shins vertical at the top'],
    mistakes: ['Arching the lower back at the top'],
    alternatives: ['romanian_deadlift', 'leg_press'],
  }),
  ex({
    id: 'standing_calf_raise',
    name: 'Standing Calf Raise',
    pattern: 'calf_raise',
    category: 'isolation',
    equipment: ['machine'],
    stability: 2,
    difficulty: 1,
    fatigue: 1,
    reps: [8, 12],
    allowed: [6, 20],
    incrementKg: 5,
    primary: ['calves'],
    setup: ['Balls of the feet on the edge, heels hanging.'],
    execution: ['Rise as high as possible, lower to a full stretch, pause.'],
    cues: ['Pause at the bottom, no bouncing'],
    mistakes: ['Bouncing out of the stretch'],
    alternatives: ['seated_calf_raise', 'leg_press_calf_raise'],
  }),
  ex({
    id: 'seated_calf_raise',
    name: 'Seated Calf Raise',
    pattern: 'calf_raise',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 5,
    primary: ['calves'],
    setup: ['Pad on the lower thighs, balls of the feet on the platform.'],
    execution: ['Rise up, lower to a full stretch with a pause.'],
    cues: ['Slow bottom'],
    mistakes: ['Short partial reps'],
    alternatives: ['standing_calf_raise', 'leg_press_calf_raise'],
  }),
  ex({
    id: 'leg_press_calf_raise',
    name: 'Leg Press Calf Raise',
    pattern: 'calf_raise',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 10,
    primary: ['calves'],
    setup: ['Balls of the feet on the bottom edge of the platform, legs nearly straight.'],
    execution: ['Push through the toes to a full point, lower to a stretch.'],
    cues: ['Knees stay nearly straight'],
    mistakes: ['Bending the knees to push'],
    alternatives: ['standing_calf_raise', 'seated_calf_raise'],
  }),
  ex({
    id: 'hip_abduction_machine',
    name: 'Hip Abduction Machine',
    pattern: 'hip_abduction',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [12, 20],
    incrementKg: 5,
    primary: ['glutes'],
    setup: ['Pads outside the knees.'],
    execution: ['Push the knees apart, return slowly.'],
    cues: ['Lean forward slightly for the glutes'],
    mistakes: ['Slamming the weight stack'],
    alternatives: ['hip_thrust'],
  }),
  ex({
    id: 'hip_adduction_machine',
    name: 'Hip Adduction Machine',
    pattern: 'hip_adduction',
    category: 'isolation',
    equipment: ['machine'],
    stability: 1,
    difficulty: 1,
    fatigue: 1,
    reps: [12, 20],
    incrementKg: 5,
    primary: ['adductors'],
    setup: ['Pads inside the knees, start at a comfortable stretch.'],
    execution: ['Squeeze the knees together, return slowly.'],
    cues: ['Control the opening'],
    mistakes: ['Starting too wide'],
    alternatives: ['goblet_squat'],
  }),

  // ---------------- Core and traps ----------------
  ex({
    id: 'cable_crunch',
    name: 'Cable Crunch',
    pattern: 'trunk_flexion',
    category: 'isolation',
    equipment: ['cable'],
    stability: 2,
    difficulty: 2,
    fatigue: 1,
    reps: [10, 15],
    incrementKg: 2.5,
    primary: ['abs'],
    secondary: ['obliques'],
    setup: ['Kneel facing a high pulley, rope held at the forehead.'],
    execution: ['Crunch the ribs toward the hips, return to a stretch.'],
    cues: ['Round the spine, hips stay still'],
    mistakes: ['Pulling with the arms', 'Hinging at the hips'],
    alternatives: ['hanging_leg_raise', 'ab_wheel_rollout'],
  }),
  ex({
    id: 'hanging_leg_raise',
    name: 'Hanging Leg Raise',
    aliases: ['hanging knee raise'],
    pattern: 'trunk_flexion',
    category: 'isolation',
    equipment: ['pullup_bar'],
    loadType: 'bodyweight',
    stability: 4,
    difficulty: 3,
    fatigue: 1,
    reps: [8, 15],
    incrementKg: 1,
    primary: ['abs'],
    secondary: ['obliques', 'forearms'],
    setup: ['Hang from the bar with a stable grip.'],
    execution: ['Raise the legs or knees by curling the pelvis up, lower slowly.'],
    cues: ['Tilt the pelvis, not just the hips'],
    mistakes: ['Swinging'],
    regressions: ['cable_crunch'],
    alternatives: ['cable_crunch', 'ab_wheel_rollout'],
  }),
  ex({
    id: 'ab_wheel_rollout',
    name: 'Ab Wheel Rollout',
    pattern: 'trunk_flexion',
    category: 'isolation',
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    stability: 4,
    difficulty: 3,
    fatigue: 1,
    reps: [8, 12],
    incrementKg: 1,
    primary: ['abs'],
    secondary: ['obliques', 'lats'],
    setup: ['Kneel with the wheel under the shoulders.'],
    execution: ['Roll out as far as the lower back stays flat, pull back.'],
    cues: ['Tuck the ribs, squeeze the glutes'],
    mistakes: ['Sagging the lower back'],
    regressions: ['plank'],
    alternatives: ['cable_crunch', 'plank'],
  }),
  ex({
    id: 'plank',
    name: 'Plank',
    pattern: 'other',
    category: 'isolation',
    equipment: ['bodyweight'],
    loadType: 'bodyweight',
    stability: 3,
    difficulty: 1,
    fatigue: 1,
    reps: [30, 60],
    allowed: [20, 120],
    incrementKg: 1,
    primary: ['abs'],
    secondary: ['obliques', 'glutes'],
    setup: ['Forearms down, elbows under the shoulders, body straight.'],
    execution: ['Hold with the glutes and abs tight. Reps are seconds.'],
    cues: ['Tuck the tailbone'],
    mistakes: ['Hips too high or sagging'],
    alternatives: ['ab_wheel_rollout', 'cable_crunch'],
  }),
  ex({
    id: 'dumbbell_shrug',
    name: 'Dumbbell Shrug',
    pattern: 'other',
    category: 'isolation',
    equipment: ['dumbbell'],
    stability: 3,
    difficulty: 1,
    fatigue: 1,
    reps: [10, 15],
    primary: ['traps'],
    secondary: ['forearms'],
    setup: ['Dumbbells at the sides, tall posture.'],
    execution: ['Shrug straight up toward the ears, pause, lower.'],
    cues: ['Straight up, no rolling'],
    mistakes: ['Rolling the shoulders'],
    alternatives: ['face_pull'],
  }),
];
