import type { ProgramTemplate, TemplateExerciseSeed } from '@/domain';

/**
 * Catalog program templates (docs/05 §9). Four at M1; three more by M5.
 * Priorities: 1 primary (never removed by compression), 2 secondary, 3 accessory.
 */

const e = (
  exerciseId: string,
  sets: number,
  min: number,
  max: number,
  opts: { priority?: 1 | 2 | 3; rir?: number; rest?: number; scheme?: TemplateExerciseSeed['progressionScheme']; superset?: string } = {},
): TemplateExerciseSeed => ({
  exerciseId,
  sets,
  repRange: { min, max },
  priority: opts.priority ?? (sets >= 3 && max <= 10 ? 1 : 2),
  targetRir: opts.rir ?? 2,
  restSeconds: opts.rest ?? (opts.priority === 3 || max >= 15 ? 75 : max <= 8 ? 150 : 105),
  progressionScheme: opts.scheme ?? 'double_progression',
  supersetGroup: opts.superset ?? null,
});

export const PROGRAM_TEMPLATES: ProgramTemplate[] = [
  {
    id: 'beginner_full_body_3x',
    name: 'Beginner Full Body',
    split: 'full_body',
    daysPerWeek: 3,
    goalTypes: ['build_muscle', 'general_fitness', 'get_stronger', 'lose_fat', 'recomp', 'maintain', 'athletic_performance'],
    experienceLevels: ['beginner'],
    sessionMinutes: 50,
    description: 'Three full-body sessions a week built around a few big movements, with weight added every session while it keeps working.',
    intent: 'Learn the main lifts, build a base of strength and muscle, and make fast early progress without excessive soreness.',
    deloadEveryWeeks: null,
    catalogVersion: 1,
    days: [
      {
        name: 'Full Body A',
        focusMuscleIds: ['quads', 'chest', 'upper_back'],
        exercises: [
          e('leg_press', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('machine_chest_press', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('lat_pulldown', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('seated_leg_curl', 2, 10, 15, { priority: 2 }),
          e('dumbbell_lateral_raise', 2, 12, 15, { priority: 3 }),
          e('cable_crunch', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Full Body B',
        focusMuscleIds: ['hamstrings', 'front_delts', 'lats'],
        exercises: [
          e('dumbbell_romanian_deadlift', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('seated_dumbbell_shoulder_press', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('seated_cable_row', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('leg_extension', 2, 10, 15, { priority: 2 }),
          e('dumbbell_curl', 2, 10, 15, { priority: 3 }),
          e('triceps_pushdown', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Full Body C',
        focusMuscleIds: ['quads', 'chest', 'upper_back'],
        exercises: [
          e('goblet_squat', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('dumbbell_bench_press', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('chest_supported_row', 3, 8, 12, { priority: 1, scheme: 'linear_load' }),
          e('lying_leg_curl', 2, 10, 15, { priority: 2 }),
          e('standing_calf_raise', 2, 10, 15, { priority: 3 }),
          e('face_pull', 2, 12, 20, { priority: 3 }),
        ],
      },
    ],
  },
  {
    id: 'full_body_3x',
    name: 'Full Body 3x',
    split: 'full_body',
    daysPerWeek: 3,
    goalTypes: ['build_muscle', 'recomp', 'lose_fat', 'general_fitness', 'maintain', 'get_stronger', 'athletic_performance'],
    experienceLevels: ['intermediate', 'advanced'],
    sessionMinutes: 60,
    description: 'Three full-body sessions with each muscle trained every session at moderate volume.',
    intent: 'Maximise growth on three days a week by hitting every muscle often with enough sets to progress.',
    deloadEveryWeeks: 6,
    catalogVersion: 1,
    days: [
      {
        name: 'Full Body A',
        focusMuscleIds: ['quads', 'chest', 'lats'],
        exercises: [
          e('barbell_back_squat', 3, 5, 8, { priority: 1 }),
          e('barbell_bench_press', 3, 6, 10, { priority: 1 }),
          e('lat_pulldown', 3, 8, 12, { priority: 2 }),
          e('seated_leg_curl', 3, 10, 15, { priority: 2 }),
          e('dumbbell_lateral_raise', 3, 12, 15, { priority: 3 }),
          e('cable_curl', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Full Body B',
        focusMuscleIds: ['hamstrings', 'front_delts', 'upper_back'],
        exercises: [
          e('romanian_deadlift', 3, 6, 10, { priority: 1 }),
          e('overhead_press', 3, 5, 8, { priority: 1 }),
          e('chest_supported_row', 3, 8, 12, { priority: 2 }),
          e('leg_press', 3, 8, 12, { priority: 2 }),
          e('triceps_pushdown', 2, 10, 15, { priority: 3 }),
          e('standing_calf_raise', 3, 8, 12, { priority: 3 }),
        ],
      },
      {
        name: 'Full Body C',
        focusMuscleIds: ['quads', 'chest', 'lats'],
        exercises: [
          e('hack_squat', 3, 8, 12, { priority: 1 }),
          e('incline_dumbbell_press', 3, 8, 12, { priority: 1 }),
          e('pull_up', 3, 5, 10, { priority: 2 }),
          e('lying_leg_curl', 2, 10, 15, { priority: 2 }),
          e('cable_lateral_raise', 3, 12, 15, { priority: 3 }),
          e('hammer_curl', 2, 10, 15, { priority: 3 }),
        ],
      },
    ],
  },
  {
    id: 'upper_lower_4x',
    name: 'Upper / Lower',
    split: 'upper_lower',
    daysPerWeek: 4,
    goalTypes: ['build_muscle', 'recomp', 'get_stronger', 'lose_fat', 'maintain', 'general_fitness', 'athletic_performance'],
    experienceLevels: ['beginner', 'intermediate', 'advanced'],
    sessionMinutes: 60,
    description: 'Two upper and two lower sessions a week, so every muscle is trained twice with room for enough volume.',
    intent: 'A balanced four-day split that fits most schedules and progresses well for years.',
    deloadEveryWeeks: 6,
    catalogVersion: 1,
    days: [
      {
        name: 'Upper A',
        focusMuscleIds: ['chest', 'lats', 'side_delts'],
        exercises: [
          e('incline_dumbbell_press', 3, 8, 12, { priority: 1 }),
          e('lat_pulldown', 3, 8, 12, { priority: 1 }),
          e('seated_cable_row', 3, 10, 12, { priority: 2 }),
          e('machine_chest_press', 2, 10, 15, { priority: 2 }),
          e('dumbbell_lateral_raise', 3, 12, 15, { priority: 3 }),
          e('triceps_pushdown', 2, 10, 15, { priority: 3 }),
          e('dumbbell_curl', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Lower A',
        focusMuscleIds: ['quads', 'hamstrings', 'calves'],
        exercises: [
          e('hack_squat', 3, 8, 12, { priority: 1 }),
          e('romanian_deadlift', 3, 6, 10, { priority: 1 }),
          e('leg_extension', 3, 10, 15, { priority: 2 }),
          e('seated_leg_curl', 3, 10, 15, { priority: 2 }),
          e('standing_calf_raise', 3, 8, 12, { priority: 3 }),
          e('cable_crunch', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Upper B',
        focusMuscleIds: ['chest', 'upper_back', 'front_delts'],
        exercises: [
          e('barbell_bench_press', 3, 6, 10, { priority: 1 }),
          e('chest_supported_row', 3, 8, 12, { priority: 1 }),
          e('seated_dumbbell_shoulder_press', 3, 8, 12, { priority: 2 }),
          e('pull_up', 2, 5, 10, { priority: 2 }),
          e('cable_fly', 2, 10, 15, { priority: 3 }),
          e('face_pull', 2, 12, 20, { priority: 3 }),
          e('overhead_cable_triceps_extension', 2, 10, 15, { priority: 3 }),
          e('incline_dumbbell_curl', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Lower B',
        focusMuscleIds: ['quads', 'glutes', 'hamstrings'],
        exercises: [
          e('leg_press', 3, 8, 12, { priority: 1 }),
          e('bulgarian_split_squat', 3, 8, 12, { priority: 2 }),
          e('lying_leg_curl', 3, 10, 15, { priority: 2 }),
          e('hip_thrust', 2, 8, 12, { priority: 2 }),
          e('seated_calf_raise', 3, 10, 15, { priority: 3 }),
          e('hanging_leg_raise', 2, 8, 15, { priority: 3 }),
        ],
      },
    ],
  },
  {
    id: 'ppl_6x',
    name: 'Push / Pull / Legs',
    split: 'ppl',
    daysPerWeek: 6,
    goalTypes: ['build_muscle', 'recomp', 'maintain', 'lose_fat', 'get_stronger'],
    experienceLevels: ['intermediate', 'advanced'],
    sessionMinutes: 60,
    description: 'Push, pull, and legs, each twice a week. High frequency and volume for people who can train six days.',
    intent: 'Maximum weekly volume per muscle with each session focused on one movement family.',
    deloadEveryWeeks: 5,
    catalogVersion: 1,
    days: [
      {
        name: 'Push A',
        focusMuscleIds: ['chest', 'front_delts', 'triceps'],
        exercises: [
          e('barbell_bench_press', 3, 6, 10, { priority: 1 }),
          e('seated_dumbbell_shoulder_press', 3, 8, 12, { priority: 2 }),
          e('cable_fly', 3, 10, 15, { priority: 2 }),
          e('dumbbell_lateral_raise', 3, 12, 15, { priority: 3 }),
          e('triceps_pushdown', 3, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Pull A',
        focusMuscleIds: ['lats', 'upper_back', 'biceps'],
        exercises: [
          e('pull_up', 3, 5, 10, { priority: 1 }),
          e('seated_cable_row', 3, 8, 12, { priority: 2 }),
          e('face_pull', 3, 12, 20, { priority: 3 }),
          e('barbell_curl', 3, 8, 12, { priority: 3 }),
          e('hammer_curl', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Legs A',
        focusMuscleIds: ['quads', 'hamstrings', 'calves'],
        exercises: [
          e('barbell_back_squat', 3, 5, 8, { priority: 1 }),
          e('romanian_deadlift', 3, 6, 10, { priority: 1 }),
          e('leg_extension', 3, 10, 15, { priority: 2 }),
          e('seated_leg_curl', 3, 10, 15, { priority: 2 }),
          e('standing_calf_raise', 4, 8, 12, { priority: 3 }),
        ],
      },
      {
        name: 'Push B',
        focusMuscleIds: ['chest', 'side_delts', 'triceps'],
        exercises: [
          e('incline_dumbbell_press', 3, 8, 12, { priority: 1 }),
          e('machine_chest_press', 3, 10, 15, { priority: 2 }),
          e('cable_lateral_raise', 4, 12, 15, { priority: 2 }),
          e('overhead_cable_triceps_extension', 3, 10, 15, { priority: 3 }),
          e('dip', 2, 6, 12, { priority: 3 }),
        ],
      },
      {
        name: 'Pull B',
        focusMuscleIds: ['lats', 'rear_delts', 'biceps'],
        exercises: [
          e('lat_pulldown', 3, 8, 12, { priority: 1 }),
          e('chest_supported_row', 3, 8, 12, { priority: 2 }),
          e('reverse_pec_deck', 3, 12, 20, { priority: 3 }),
          e('incline_dumbbell_curl', 3, 10, 15, { priority: 3 }),
          e('dumbbell_shrug', 2, 10, 15, { priority: 3 }),
        ],
      },
      {
        name: 'Legs B',
        focusMuscleIds: ['quads', 'glutes', 'hamstrings'],
        exercises: [
          e('hack_squat', 3, 8, 12, { priority: 1 }),
          e('hip_thrust', 3, 8, 12, { priority: 2 }),
          e('lying_leg_curl', 3, 10, 15, { priority: 2 }),
          e('bulgarian_split_squat', 2, 8, 12, { priority: 3 }),
          e('seated_calf_raise', 4, 10, 15, { priority: 3 }),
          e('cable_crunch', 3, 10, 15, { priority: 3 }),
        ],
      },
    ],
  },
];
